server:
  port: 8081

spring:
  application:
    name: server-eureka
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  jpa:
    database: mysql
    show-sql: true
    hibernate:
    ddl-auto: update

  mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
    config-locations: classpath:mybatis/confg.xml
